print('Pirmas kartas')
print('naujas')
print('I\'m \"a\" programmer')
print('c:\\user\\new\\data.txt')
#komentaras
print("Tekstas", end=' ')
print("vienoje", end=' ')
print('eiluteje')
print("Tekstas \nkeliose \neilutese")
print('pirmas','antras')
print('pirmas' + 'antras')